### ISSUE TITLE
macOS can't make

### ISSUE THREAD

**Issue by LuoZijun** [mikeakohn/mandelbrot_sse#1]
```bash
make
```

OutPut:

    nasm -f macho64 render_mandelbrot_sse.asm
    nasm: fatal: unrecognised output format `macho64' - use -hf for a list
    type `nasm -h' for help
    make: *** [mac] Error 1

Device: MacBook Air (13-inch, Early 2014)
OS:  macOS Sierra ( Ver: 10.12.1 )

Hardware Info:

    hw.ncpu: 4
    hw.byteorder: 1234
    hw.memsize: 8589934592
    hw.activecpu: 4
    hw.optional.sgx: 0
    hw.optional.mpx: 0
    hw.optional.adx: 1
    hw.optional.hle: 0
    hw.optional.rtm: 0
    hw.optional.bmi2: 1
    hw.optional.bmi1: 1
    hw.optional.avx2_0: 1
    hw.optional.fma: 1
    hw.optional.enfstrg: 1
    hw.optional.f16c: 1
    hw.optional.rdrand: 1
    hw.optional.avx1_0: 1
    hw.optional.aes: 1
    hw.optional.x86_64: 1
    hw.optional.sse4_2: 1
    hw.optional.sse4_1: 1
    hw.optional.supplementalsse3: 1
    hw.optional.sse3: 1
    hw.optional.sse2: 1
    hw.optional.sse: 1
    hw.optional.mmx: 1
    hw.optional.floatingpoint: 1
    hw.packages: 1
    hw.tbfrequency: 1000000000
    hw.l3cachesize: 3145728
    hw.l2cachesize: 262144
    hw.l1dcachesize: 32768
    hw.l1icachesize: 32768
    hw.cachelinesize: 64
    hw.cpufrequency_max: 1400000000
    hw.cpufrequency_min: 1400000000
    hw.cpufrequency: 1400000000
    hw.busfrequency_max: 100000000
    hw.busfrequency_min: 100000000
    hw.busfrequency: 100000000
    hw.pagesize32: 4096
    hw.pagesize: 4096
    hw.cachesize: 8589934592 32768 262144 3145728 0 0 0 0 0 0
    hw.cacheconfig: 4 2 2 4 0 0 0 0 0 0
    hw.cpufamily: 280134364
    hw.cpu64bit_capable: 1
    hw.cpusubtype: 8
    hw.cputype: 7
    hw.logicalcpu_max: 4
    hw.logicalcpu: 4
    hw.physicalcpu_max: 2
    hw.physicalcpu: 2
    hw.targettype: Mac
    hw.cputhreadtype: 1

**Comment by mikeakohn** [comment]
The version of nasm that comes with macOS Sierra is 0.98.40.  The version of nasm I use is 2.12.01.  Please download and install the latest version of nasm.

**Comment by LuoZijun** [comment]
@mikeakohn ok, thx.
